### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by baronin** [baronin/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by PostMix** [comment]
И сделать их кликабельными, потому что на телефоне копировать и куда-то вставлять - это боль.

**Comment by baronin** [comment]
Согласен
